LOAD DATA LOCAL INFILE 'Items2.dat' INTO TABLE Items FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'Sellers2.dat' INTO TABLE Sellers FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'Categories2.dat' INTO TABLE Categories FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'Bidders2.dat' INTO TABLE Bidders FIELDS TERMINATED BY '|*|';
LOAD DATA LOCAL INFILE 'Bids2.dat' INTO TABLE Bids FIELDS TERMINATED BY '|*|';